version: '3.4'

services:
  # to use the wait-for-it helper on CircleCI
  wait:
    image: deliveroo/circleci:latest
    links:
      - db

  app:
    build:
     context: .
     dockerfile: Dockerfile
    working_dir: /app
    environment:
      - APP_ENV=test