version: 2

services:
  - type: Hopper::Services::ECS::Service
    name: web
    taskDefinition:
      containerDefinitions:
        - name: web
          cpu: "{{ ternary 6144 2048 (eq .environment 'platform') }}"
          memory: "{{ ternary 16384 4096 (eq .environment 'platform') }}"