# Generated by Django 4.2.13 on 2024-06-30 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_lead',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_lead', to='first_app.employee'),
        ),
    ]
